// <auto-generated />
using System;
using AcmeRemoteFilghts.DataLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AcmeRemoteFilghts.Migrations
{
    [DbContext(typeof(AcmeDbContext))]
    [Migration("20180624085554_changeCityName")]
    partial class changeCityName
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AcmeRemoteFilghts.DataLayer.Entities.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Bookedby");

                    b.Property<DateTime>("FlightDate");

                    b.Property<int>("FlightId");

                    b.Property<int>("NoTickets");

                    b.HasKey("Id");

                    b.HasIndex("FlightId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("AcmeRemoteFilghts.DataLayer.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CityName");

                    b.HasKey("Id");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("AcmeRemoteFilghts.DataLayer.Entities.Flight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("ArriveTime");

                    b.Property<int>("CityFromId");

                    b.Property<int>("CityToId");

                    b.Property<DateTime>("DepartTime");

                    b.Property<int>("MaxPassangers");

                    b.HasKey("Id");

                    b.ToTable("Flights");
                });

            modelBuilder.Entity("AcmeRemoteFilghts.DataLayer.Entities.Booking", b =>
                {
                    b.HasOne("AcmeRemoteFilghts.DataLayer.Entities.Flight", "flight")
                        .WithMany("Bookings")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
